<?php
define('ERREUR_EMAIL', 1);
define('ERREUR_TELEPHONE', 2);
define('ERREUR_CHAMP_VIDE', 3);
define('ERREUR_ENREGISTREMENT', 4);
define('ERREUR_PASSWORD_LENGTH', 5);
define('ERREUR_PASSWORD_IDENTIQUE', 6);
